name: Python CI

on:
  push:
    branches: [master]
  pull_request:
    branches:
    - '**'

jobs:
  run_tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        python-version: ['3.11', '3.12']
        toxenv: [django42, quality, csslint, eslint]

    steps:
    - uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set BOTO_CONFIG value
      run: export BOTO_CONFIG=/dev/null

    - name: Install pip
      run: pip install -r requirements/pip.txt

    - name: Install Dependencies
      run: make requirements_ci

    - name: Run Tests
      env:
        TOXENV: ${{ matrix.toxenv }}
      run: tox
